# -------------------------------------
# スクリプト実行時などインタラクティブシェルの場合はbashrcを読み込まない
# -------------------------------------
case $- in
    *i*) ;;
      *) return;;
esac

# -------------------------------------
# 履歴管理
# -------------------------------------
# 先頭にスペースがある場合と直前と同じコマンドは履歴に残さない
HISTCONTROL=ignoreboth
# 履歴情報を上書きするので別のターミナルで実行した結果も残す
shopt -s histappend
# 履歴情報を残すサイズ
HISTSIZE=10000
HISTFILESIZE=20000

# -------------------------------------
# aliasの設定
# -------------------------------------
# nvimのエイリアスの設定
alias vim='nvim'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# -------------------------------------
# 環境変数の読み込み
# -------------------------------------
# Git管理したくない環境変数はファイルに定義する
if [ -f ~/.environments ]; then
    . ~/.environments
fi

# -------------------------------------
# その他の設定
# -------------------------------------
# 画面サイズが変更された場合に自動で表示を更新する設定
shopt -s checkwinsize

# lessコマンドでバイナリや圧縮ファイルを適切に処理するようにする
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
#
# コマンドの色情報の設定
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# -------------------------------------
# プロンプトの設定
# -------------------------------------
if [ -f ~/dotfiles/bash/prompt ]; then
    . ~/dotfiles/bash/prompt
fi


# -------------------------------------
# Bashの補完機能の設定
# -------------------------------------
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# -------------------------------------
# Cargoの設定（Rust）
# -------------------------------------

. "$HOME/.local/bin/env"
. "$HOME/.cargo/env"

# -------------------------------------
# fzfの設定
# git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
# ~/.fzf/install
# -------------------------------------
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
